- name: Creating DNS Record
  community.general.nios_a_record:
    name: "{{a_rec}}"
    ipv4addr: "{{a_ip}}"
    comment: "{{a_comment}}"
    state: present
    ttl: "{{a_ttl}}"
    provider: "{{provider}}"
  register: dns_change
  notify: a_rec_query
# - debug:
#     msg: "{{dns_change}}"
